### PR TITLE
Clean: Meta - Rename: `/icons` -> `/leptonIcons`, `/css` -> `/leptonCss`

### PR DESCRIPTION
**Pull request by bb010g**
## Describe the PR

I install Lepton by symlinking files & directories from `$firefoxUiFix/` to `$firefoxProfile/chrome/`, which allows me, a technical user, to update Lepton and maintain patches on top of it easily. This includes symlinking directories like `$firefoxUiFix/icons` to `$firefoxProfile/chrome/icons`. However, this naming makes use of Lepton alongside other user CSS tweaks difficult. If `/icons` is renamed to `/leptonIcons`, then `$firefoxUiFix/leptonIcons` can be symlinked to ` $firefoxProfile/chrome/leptonIcons` and collisions are avoided with other custom icon sets in the `$firefoxProfile/chrome` directory. I'm submitting this change to upstream because renaming `/icons` to `/leptonIcons` requires changing `../icons` to `../leptonIcons` in the SCSS source. I understand this installation method is unsupported, and this patch set does not attempt to make it supported, and instead only makes the method more convenient for those trying it anyways.

Additionally, `/css` is renamed to `/leptonCss` for parity. There are only two files in `/leptonCss`, as opposed to the high & variable amount in `/leptonIcons`, but it maintains consistency and doesn't appear to have any downsides (aside from potentially breaking unsupported installation methods, like my symlink approach, that have already been silently broken by changes in the past). This change occurs in a separate commit for the benefit of Git's rename detection.

Additionally, the build output directory `/css/*` (now `/leptonCss/*`) is marked as `linguist-generated`, for the benefit of GitHub's statistics & rendering. (See <https://github.com/github/linguist/blob/c1c34e5260797b4d598f5ec76f19723bfc5a1894/docs/overrides.md>.) This commit can be dropped if it's unwanted.

## PR Type

- [ ] `Add:` Add feature or enhanced.
- [ ] `Fix:` Bug fix or change default values.
- [x] `Clean:` Refactoring.
  - GitHub - Mark `/css/*` as generated
  - Meta - Rename: `/icons` -> `/leptonIcons`
  - Meta - Rename: `/css` -> `/leptonCss`
- [ ] `Doc:` Update docs.

### CODE REVIEW

**Comment by thunderstone135** [comment]
This should be put on a vote.

**Comment by thunderstone135** [comment]
Just like this [one](https://github.com/black7375/Firefox-UI-Fix/discussions/525).

**Comment by black7375** [comment]
In my opinion, I wonder if this change is actually helpful for custom.
If the namespace overlaps, isn't it possible to manage like `<firefox_profile>/chrome/customIcons` and `<firefox_profile>/chrome/customCSS`?

**Comment by bb010g** [comment]
> In my opinion, I wonder if this change is actually helpful for custom.

This is a change that's made my specific workflow easier for a number of months. I can't speak for others.

>If the namespace overlaps, isn't it possible to manage like `<firefox_profile>/chrome/customIcons` and `<firefox_profile>/chrome/customCSS`?

I went with `lepton` as a prefix because it was already used by `leptonChrome.css` and `leptonContent.css`. Also, I think that if we're namespacing, it makes more sense to use a more specific namespace that will inherently be less likely to collide. `customIcons` is more generic, and while it might work, it's also more likely to collide.

**Comment by black7375** [comment]
After a little consideration, I don't think there's enough benefit to change the directory name.
But the suggestion for `.gitattributes` is good.

Therefore,  I added only [`55e2699`](https://github.com/black7375/Firefox-UI-Fix/pull/606/commits/55e2699af63a8c393e7ff65f060cb21ab04f0c30) commit as cherry-pick and added you as a contributor.
Thank you for waiting for a long time.

**Comment by bb010g** [comment]
> After a little consideration, I don't think there's enough benefit to change the directory name. But the suggestion for `.gitattributes` is good.
> 
> Therefore, I added only [`55e2699`](https://github.com/black7375/Firefox-UI-Fix/pull/606/commits/55e2699af63a8c393e7ff65f060cb21ab04f0c30) commit as cherry-pick and added you as a contributor. Thank you for waiting for a long time.

Thanks for cherry-picking the `.gitattributes` change in, and no worries about the delay.

Would just a `leptonIcons`-style change be more acceptable? That's my main pain point when rebasing my symlink-compatiblity patch. Perhaps the directory name could be parameterized at the Sass level? It'd offer a similar benefit to the patch proposed here in that it's easy to grep for `leptonIcons` to see where Lepton icons are used instead of built-in Firefox icons (currently, path strings for both contain `/icons`: Firefox is (mostly) `chrome://global/skin/icons/`, while Lepton is `../icons/`).

In any case, thank you for your consideration and continued maintenance.

**Comment by black7375** [comment]
To more accurately describe the intention,
I don't want to put a burden on them because there are cases where I can refer to or fork my project.

- https://github.com/BPower0036/UserChrome/
- https://github.com/te6-in/lepton-custom
- https://github.com/Hou-Rui/lepton-oneline

**Pull request closed without merging**
