### PR TITLE
Ver 6.0.0 Feedback Thread

### PR DESCRIPTION
**Pull request by black7375**
**Describe the PR**

As mentioned in #380 , It aim to provide a minimal UI.  
Inspired by [Mozilla Labs](https://www.mozillalabs.com/en-US/projects/index.html)'s [Prospector: OneLiner](https://www.mozillalabs.com/oneliner/index.html)([Blog](https://web.archive.org/web/20120128044114/https://www.mozillalabs.com/prospector/2011/07/28/oneliner-moves-navigation-to-the-tabs-toolbar/)), [Prospector: LessChrome HD](https://www.mozillalabs.com/lesschrome-hd/index.html)([Blog](https://web.archive.org/web/20120331223118/https://www.mozillalabs.com/prospector/2011/05/20/lesschrome-hd-more-space-to-browse/)) projects and [Microsoft Edge Vertical Tab](https://microsoftedgetips.microsoft.com/en-us/collections/productivity/i310?form=MA13DX).

-  One liner UI
   - `userChrome.tabbar.one_liner`
   - `userChrome.tabbar.one_liner.combine_navbar`
   - `userChrome.tabbar.one_liner.tabbar_first`
   - `userChrome.tabbar.one_liner.responsive`
-  Auto Hide UI
   - `userChrome.autohide.tab`
   - `userChrome.autohide.tab.opacity`
   - `userChrome.autohide.tab.blur`
   - `userChrome.autohide.tabbar`
   - `userChrome.autohide.navbar`
   - `userChrome.autohide.bookmarkbar`
   - `userChrome.autohide.sidebar`
   - `userChrome.autohide.fill_urlbar`
   - `userChrome.autohide.back_button`
   - `userChrome.autohide.forward_button`
   - `userChrome.autohide.page_action`
   - `userChrome.autohide.toolbar_overlap`
- Hidden UI
   - `userChrome.hidden.tab_icon`
   - `userChrome.hidden.tab_icon.always`
   - `userChrome.hidden.tabbar`
   - `userChrome.hidden.navbar`
   - `userChrome.hidden.sidebar_header`
   - `userChrome.hidden.sidebar_header.vertical_tab_only`
   - `userChrome.hidden.urlbar_iconbox`
   - `userChrome.hidden.bookmarkbar_icon`
   - `userChrome.hidden.bookmarkbar_label`
   - `userChrome.hidden.disabled_menu`
   - `userChrome.tabbar.on_bottom.hidden_single_tab`
- Monospace
   - `userChrome.theme.monospace`
   - `userContent.page.monospace`
-  Centered UI
   - `userChrome.centered.tab`
   - `userChrome.centered.tab.label`
   - `userChrome.centered.urlbar`
   - `userChrome.centered.bookmarkbar`
- Vertical Tab support
   - `userChrome.tabbar.as_titlebar`
   - `userChrome.sidebar.overlap`
   - Icons for [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/), [Tab Center Reborn](https://addons.mozilla.org/en-US/firefox/addon/tabcenter-reborn/), [Sidebar Tabs](https://addons.mozilla.org/en-US/firefox/addon/sidebartabs/)

It is not yet stabilized API, and there may be changes before merging.

---

Some API has been breaking change.

- `userChrome.tab.on_bottom` -> `userChrome.tabbar.on_bottom`
- `userChrome.tab.on_bottom.above_bookmark` -> `userChrome.tabbar.on_bottom.above_bookmark`
- `userChrome.tab.on_bottom.menubar_on_top` -> `userChrome.tabbar.on_bottom.menubar_on_top`
- `userChrome.tab.centered_label` -> `userChrome.centered.tab.label`

---

Setup - Please refer [Wiki:Installation Guide](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide)

```shell
## First user ##################################################################
# At <FIREFOX_PROFILE_DIRECTORY>

# Original dev version
git clone https://github.com/black7375/Firefox-UI-Fix -b dev

# Photon style dev version
git clone https://github.com/black7375/Firefox-UI-Fix  chrome -b photon-style-dev

# Proton style dev version
git clone https://github.com/black7375/Firefox-UI-Fix chrome -b proton-style-dev

## Existing user ###############################################################
# At <FIREFOX_PROFILE_DIRECTORY>/chrome

# Original dev version
git checkout dev
git pull

# Proton style dev version
git checkout photon-style-dev
git pull

# Proton style dev version
git checkout proton-style-dev
git pull
```
---

**Related Issue**

- #327
- #386

**Screenshots**

I'd like to show you some use cases.

- Oneliner + Tabs on bottom
   - `userChrome.tabbar.one_liner`
   - `userChrome.tabbar.one_liner.responsive`
   - `userChrome.tabbar.on_bottom`

https://user-images.githubusercontent.com/25581533/182741363-8396a2c7-1a0d-4931-ae81-692f4e721384.mp4

- Oneliner  + Centered
   - `userChrome.tabbar.one_liner`
   - `userChrome.tabbar.one_liner.combine_navbar`
   - `userChrome.autohide.forward_button`
   - `userChrome.centered.tab`
   - `userChrome.centered.tab.label`
   - `userChrome.centered.bookmarkbar`

image

- Autohide navbar + Centered
   - `userChrome.autohide.tab`
   - `userChrome.autohide.tab.blur`
   - `userChrome.autohide.navbar`
   - `userChrome.centered.tab`
   - `userChrome.centered.tab.label`
   - `userChrome.centered.bookmarkbar`

image

- Vertical Tab
   - `userChrome.tabbar.as_titlebar`
    - `userChrome.centered.tab`
   - `userChrome.autohide.sidebar`
   - `userChrome.sidebar.overlap`
   - `userChrome.hidden.sidebar_header`
   - `userChrome.hidden.sidebar_header.vertical_tab_only`

image

**Additional context**

You can suggest compatibility issues, option names, etc.

### CODE REVIEW

**Comment by Zabooby** [comment]
Any plans to make it so that the urlbar only shows on hover or when in focus, so tabs can take up the whole row?

**Comment by black7375** [comment]
LGTM
I will try to add it as an option tomorrow.

**Comment by black7375** [comment]
I checked and the feature works limited.
It can't adjust the size of the tab layout without sacrificing the title menu bar or other compatibility.

An alternative that does not sacrifice compatibility is that navbar works with overlap mode.

https://user-images.githubusercontent.com/25581533/184047081-3bc13b4b-9eb9-4fc8-8abe-02415af5aecb.mp4

**Comment by Zabooby** [comment]
Hm I think the one i linked looks smoother, would it be possible to just copy it over and just try and make the url bar as small as possible?

Another way you could hide it is like [this](https://github.com/Etesam913/slick-fox), I guess that wouldn't be a oneliner though.

Also I remember there being some css stuff [here ](https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome)related to the url bar that might help.

**Comment by black7375** [comment]
Autohide like [slickfox](https://github.com/Etesam913/slick-fox) are already fully supported.

https://user-images.githubusercontent.com/25581533/184078300-f37ffbaa-36c1-4674-b4f4-49f25b5a7c85.mp4

The problem is that the layout adjustment of the `Tab Bar` is not possible without sacrificing compatibility only if it is a hover of `Nav Bar`.

**Comment by Zabooby** [comment]
I see, would you be able to fix those issues and is it even possible to get the url bar to auto hide the way I described it without any problems?

And will version 6 have 2 possible onliners the slickfox version and something like [cascade ](https://github.com/andreasgrafen/cascade)?

**Pull request merged**
