### PR TITLE
Fix: Panel - Fix text cut off in some language #28

### LINKED ISSUE #28: Menu entry in german translation cut off
**Describe the bug**
The menu entry "Neues privates Fenster" is shrinked to "Neues privates Fens...".
See the attached screenshot

**Expected behavior**
"Neues privates Fens..." should appear as "Neues privates Fenster"

**Environment (please complete the following information):**
 - Firefox Version: 89.0
 - OS:
   - [x] Linux
 - Theme:
   - [x] System Default
     - GTK Theme Name(Only Linux User): [sample] Adwaita, Adwaita-Dark, Breath, Breath-Dark

menu

### PR DESCRIPTION
**Pull request by SimYunSup**
Fix #28 issue.

### CODE REVIEW

**Comment by 7k5x** [comment]
This could make the menu bar wider and Most people who do not use German could be uncomfortable with it. How about only widening the menu when the locale is German? I think that's possible in CSS.

**Comment by black7375** [comment]
Up to `25em` seems like a negotiable size.
I honestly don't understand why Mozilla made it truncated even by default.

**Comment by terr72** [comment]
@black7375 Actually the width is sufficient for stock FF, but after re-adding the icons the text gets truncated.

**Comment by black7375** [comment]
@terr72 
It has never happened in the language I use(English, Korean), but there are reports that there is a problem in Japanese.
https://github.com/black7375/Firefox-UI-Fix/issues/28#issuecomment-853333286

**Comment by SimYunSup** [comment]
grafik

@terr72 If you make width `30em`, All the truncated text is disappeared. But it's too wide in main panel and other panels, too.

**Comment by black7375** [comment]
I've been using it for a few days now and it seems a bit wide.

Looking back at the issue I found the following comment https://github.com/black7375/Firefox-UI-Fix/issues/28#issuecomment-853245691
> Also 23em is sufficient (at least for Linux, not tested with Windows).


So, German seems to work on `23em`.

@ SimYunSup 
What if I change the value to `23em`, and `25em` add it to the [Wiki:Compatibility-Issues-Solution](https://github.com/black7375/Firefox-UI-Fix/wiki/Compatibility-Issues-Solution)?

**Comment by SimYunSup** [comment]
@black7375 If you think this project must be english in the standard, It will be better to revert to original.
image

But I think your idea of putting it on wiki is good.

**Comment by black7375** [comment]
Thanks for the screenshot.
Then adjust the value a little and move the current value to Wiki.

**Comment by black7375** [comment]
@SimYunSup 
I recently created a [CREDIT file](https://github.com/black7375/Firefox-UI-Fix/blob/master/CREDITS).
It is based on the commit log and github profile, please make sure the information is correct.

**Comment by SimYunSup** [comment]
@black7375  It's correct. Thank you for giving chance to contribute.

**Comment by black7375** [comment]
No thanks

**Pull request merged**
