### PR TITLE
 Ver 7.0.0 Feedback Thread

### PR DESCRIPTION
**Pull request by black7375**
**Describe the PR**

As mentioned in #453 , The purpose is to implement various UI.

Tab #326
- `userChrome.tab.bar_separator`
- `userChrome.tab.bottom_rounded_corner.all`
- `userChrome.tab.bottom_rounded_corner.australis`
- `userChrome.tab.bottom_rounded_corner.edge`
- `userChrome.tab.bottom_rounded_corner.chrome`
- `userChrome.tab.bottom_rounded_corner.chrome_legacy`
- `userChrome.tab.bottom_rounded_corner.wave`
- `userChrome.tab.close_button_at_hover.with_selected`

Tab Bar
- `userChrome.tabbar.fill_width"` #458
- `userChrome.tabbar.multi_row` #315
- `userChrome.tabbar.unscroll`

URL Bar & View
- `userChrome.hidden.urlbar_iconbox.label_only`
- `userChrome.rounding.square_urlView_item`
- `userChrome.urlbar.iconbox_with_separator`
- `userChrome.urlView.as_commandbar`
- `userChrome.urlView.full_width_padding`
- `userChrome.urlView.focus_item_border`

Photon like components #399
- `userChrome.decoration.panel_button_separator`
- `userChrome.decoration.panel_arrow`

Counter
- `userChrome.counter.tab`
- `userChrome.counter.bookmark_menu`

Combined
- `userChrome.combined.nav_button`
- `userChrome.combined.nav_button.home_button`
- `userChrome.combined.urlbar.nav_button`
- `userChrome.combined.urlbar.home_button`
- `userChrome.combined.urlbar.reload_button`
- `userChrome.combined.sub_button.none_background`
- `userChrome.combined.sub_button.as_normal`

Others
- `userChrome.padding.toolbar_button.compact`
- `userChrome.navbar.as_sidebar`
- `userChrome.bookmarkbar.multi_row`
- `userChrome.findbar.floating_on_top`
- `userChrome.hidden.titlebar_container` #550

It is ***not yet stabilized API***, and there may be changes before merging.

---

Setup - Please refer [Wiki:Installation Guide](https://github.com/black7375/Firefox-UI-Fix/wiki/Installation-Guide)

```shell
## First user ##################################################################
# At <FIREFOX_PROFILE_DIRECTORY>

# Original dev version
git clone https://github.com/black7375/Firefox-UI-Fix -b dev

# Photon style dev version
git clone https://github.com/black7375/Firefox-UI-Fix  chrome -b photon-style-dev

# Proton style dev version
git clone https://github.com/black7375/Firefox-UI-Fix chrome -b proton-style-dev

## Existing user ###############################################################
# At <FIREFOX_PROFILE_DIRECTORY>/chrome

# Original dev version
git checkout dev
git pull

# Proton style dev version
git checkout photon-style-dev
git pull

# Proton style dev version
git checkout proton-style-dev
git pull
```
---

**Screenshots**

I'd like to show you some use cases.

- **Keyboard browsing**

Inspired by [qutebrowser](https://www.qutebrowser.org/).

You can browse only with the keyboard using the [Vim](https://www.vim.org/) shortcut and [Caret Browsing](https://www.online-tech-tips.com/computer-tips/what-is-caret-browsing-and-how-to-use-it/).

https://user-images.githubusercontent.com/25581533/202938054-d0a28a08-9c4e-4514-8e7d-cc615b22e694.mp4

If you want `Status Bar`, use [Waterfox](https://www.waterfox.net/)

- **Theme:** [Matte Black (Green)](https://addons.mozilla.org/en-US/firefox/addon/matte-black-green/)
- **Addon:** [Vim Vixen](https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/)
  - Or [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/), [Vimium-FF](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/), [Saka Key](https://addons.mozilla.org/en-US/firefox/addon/saka-key/), [Surfingkeys](https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/)

<details><summary><b>user.js</b></summary>

```javascript
// ** Browser Options **********************************************************
user_pref("browser.uidensity",                            1); // and urlbar spacing. The possible values are 0=normal, 1=compact, 2=touch.
user_pref("browser.tabs.inTitlebar",                      0); // no (0), yes (1), or default (2), which is true everywhere except Linux.
user_pref("accessibility.browsewithcaret",             true);

// Waterfox only
user_pref("browser.statusbar.enabled",                 true);
user_pref("browser.statusbar.appendStatusText",        true);

// == Theme Distribution Settings ==============================================
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",        true); // Original
user_pref("userChrome.tab.photon_like_padding",       false); // Photon

user_pref("userChrome.tab.dynamic_separator",         false); // Original, Proton
user_pref("userChrome.tab.static_separator",          false); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option
user_pref("userChrome.tab.bar_separator",              true); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",    false); // Original
user_pref("userChrome.tab.newtab_button_smaller",      true); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",                true); // Original, Proton
user_pref("userChrome.icon.panel_photon",             false); // Photon
user_pref("userChrome.icon.panel_sparse",             false); // Just option

// Original Only
user_pref("userChrome.tab.box_shadow",                false);
user_pref("userChrome.tab.bottom_rounded_corner",     false);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",   false);
user_pref("userChrome.rounding.square_tab",            true);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.theme.monospace",                     true);

user_pref("userChrome.hidden.navbar",                       true);

user_pref("userChrome.counter.tab",                         true);
user_pref("userChrome.counter.bookmark_menu",               true);

user_pref("userChrome.tabbar.fill_width",                   true);

// -- User Content -------------------------------------------------------------
user_pref("userContent.page.monospace",                     true);
```

</details>

- **Photon with multirow**

Photon style to support multirow.

https://user-images.githubusercontent.com/25581533/203427201-ea494c3d-c56f-41a2-bcb7-852f58931bbc.mp4

<details><summary><b>user.js</b></summary>

```javascript
// ** Browser Options **********************************************************
user_pref("browser.search.widget.inNavBar",            true);

// == Theme Distribution Settings ==============================================
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",       false); // Original
user_pref("userChrome.tab.photon_like_padding",        true); // Photon

user_pref("userChrome.tab.dynamic_separator",         false); // Original, Proton
user_pref("userChrome.tab.static_separator",           true); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",    false); // Original
user_pref("userChrome.tab.newtab_button_smaller",      true); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",               false); // Original, Proton
user_pref("userChrome.icon.panel_photon",              true); // Photon

// Original Only
user_pref("userChrome.tab.box_shadow",                false);
user_pref("userChrome.tab.bottom_rounded_corner",     false);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",    true);
user_pref("userChrome.rounding.square_tab",            true);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.decoration.panel_button_separator",   true);
user_pref("userChrome.decoration.panel_arrow",              true);

user_pref("userChrome.combined.nav_button",                 true);
user_pref("userChrome.combined.sub_button.as_normal",       true);

user_pref("userChrome.padding.urlView_expanding",           true);
user_pref("userChrome.padding.urlView_result",              true);
user_pref("userChrome.padding.toolbar_button.compact",      true);

user_pref("userChrome.urlView.always_show_page_actions",    true);
user_pref("userChrome.urlView.move_icon_to_left",           true);

user_pref("userChrome.rounding.square_panel",               true);
user_pref("userChrome.rounding.square_panelitem",           true);

user_pref("userChrome.panel.full_width_separator",          true);
user_pref("userChrome.panel.full_width_padding",            true);

user_pref("userChrome.tabbar.multi_row",                    true);
user_pref("userChrome.bookmarkbar.multi_row",               true);

```

</details>

- **Australis like theme**

Set up combined UI like [Australis](https://wiki.mozilla.org/Firefox/Features/Theme_Refinement_and_Evolution_(Australis)).  
At the same time, it applies a gaming feeling like [Opera GX](https://www.opera.com/gx).

https://user-images.githubusercontent.com/25581533/203198591-aceba22b-bf0a-4b5a-a990-4e228b045fc9.mp4

- **Theme:** [Beautiful Opera GX Fucsia](https://addons.mozilla.org/en-US/firefox/addon/beautiful-opera-gx-fucsia/)

<details><summary><b>user.js</b></summary>

```javascript
// ** Browser Options **********************************************************
user_pref("browser.tabs.inTitlebar",                      1); // no (0), yes (1), or default (2), which is true everywhere except Linux.
user_pref("browser.search.widget.inNavBar",            true);

// == Theme Distribution Settings ==============================================
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",        true); // Original
user_pref("userChrome.tab.photon_like_padding",       false); // Photon

user_pref("userChrome.tab.dynamic_separator",          true); // Original, Proton
user_pref("userChrome.tab.static_separator",          false); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option
user_pref("userChrome.tab.bar_separator",             false); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",     true); // Original
user_pref("userChrome.tab.newtab_button_smaller",     false); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",                true); // Original, Proton
user_pref("userChrome.icon.panel_photon",             false); // Photon
user_pref("userChrome.icon.panel_sparse",             false); // Just option

// Original Only
user_pref("userChrome.tab.box_shadow",                 true);
user_pref("userChrome.tab.bottom_rounded_corner",      true);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",   false);
user_pref("userChrome.rounding.square_tab",           false);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.autohide.forward_button",             true);

user_pref("userChrome.combined.urlbar.nav_button",          true);
user_pref("userChrome.combined.urlbar.reload_button",       true);

user_pref("userChrome.tab.bottom_rounded_corner.all",       true);
user_pref("userChrome.tab.bottom_rounded_corner.australis", true);

user_pref("userChrome.urlbar.iconbox_with_separator",       true);

// Option
// user_pref("userChrome.combined.urlbar.home_button",         true);

```

</details>

<details><summary><b>userChrome.css</b></summary>

```css
/* Original:
At :root
  --toolbar-field-focus-border-color: rgba(0, 0, 0, 0);
  --buttons-destructive-active-bgcolor: #810220;
  --toolbar-field-background-color: rgba(0, 0, 0, 0);
  --arrowpanel-background: rgba(28, 23, 38, 0.9959999918937683);

At #navigator-toolbox
  --lwt-tabs-border-color: rgba(208, 26, 67, 0.6669999957084656);

At #TabsToolbar, Need hardcoded
  --lwt-tab-line-color: rgb(208, 26, 67);
  */

#nav-bar {
  --toolbar-field-focus-border-color: var(--buttons-destructive-active-bgcolor);
  --toolbar-field-background-color: var(--arrowpanel-background);
  --lwt-tabs-border-color: rgb(208, 26, 67);
}
```

</details>

- **Chrome like theme**

Minimal settings to get a look and fill for [Chrome](https://www.google.com/intl/en_US/chrome/).

https://user-images.githubusercontent.com/25581533/202938205-f87f4676-0a92-417c-8c8e-0be2d12671f6.mp4

- **Theme:** [Google Chrome Dark](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-dark/)
  - Or [Google Chrome Light](https://addons.mozilla.org/en-US/firefox/addon/google-chrome-light/), [Chrome Just Black](https://addons.mozilla.org/en-US/firefox/addon/chrome-just-black/)

<details><summary><b>user.js</b></summary>

```javascript
// ** Browser Options **********************************************************
user_pref("browser.tabs.inTitlebar",                      1); // no (0), yes (1), or default (2), which is true everywhere except Linux.

// Experimental settings for `userChrome.tabbar.unscroll`
user_pref("layout.css.container-queries.enabled",      true);
user_pref("layout.css.overflow-moz-hidden-unscrollable.enabled", true);
user_pref("browser.tabs.tabMinWidth",                     0);

// == Theme Distribution Settings ==============================================
user_pref("userChrome.tab.connect_to_window",          true); // Original, Photon
user_pref("userChrome.tab.color_like_toolbar",         true); // Original, Photon

user_pref("userChrome.tab.lepton_like_padding",        true); // Original
user_pref("userChrome.tab.photon_like_padding",       false); // Photon

user_pref("userChrome.tab.dynamic_separator",          true); // Original, Proton
user_pref("userChrome.tab.static_separator",          false); // Photon
user_pref("userChrome.tab.static_separator.selected_accent", false); // Just option
user_pref("userChrome.tab.bar_separator",             false); // Just option

user_pref("userChrome.tab.newtab_button_like_tab",    false); // Original
user_pref("userChrome.tab.newtab_button_smaller",      true); // Photon
user_pref("userChrome.tab.newtab_button_proton",      false); // Proton

user_pref("userChrome.icon.panel_full",                true); // Original, Proton
user_pref("userChrome.icon.panel_photon",             false); // Photon
user_pref("userChrome.icon.panel_sparse",             false); // Just option

// Original Only
user_pref("userChrome.tab.box_shadow",                 true);
user_pref("userChrome.tab.bottom_rounded_corner",      true);

// Photon Only
user_pref("userChrome.tab.photon_like_contextline",   false);
user_pref("userChrome.rounding.square_tab",           false);

// == Theme Custom Settings ====================================================
// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.rounding.square_urlView_item",        true);

user_pref("userChrome.urlView.full_width_padding",          true);
user_pref("userChrome.urlView.focus_item_border",           true);

user_pref("userChrome.tab.bottom_rounded_corner.all",       true);
user_pref("userChrome.tab.bottom_rounded_corner.chrome",    true);

user_pref("userChrome.tabbar.unscroll",                     true);

user_pref("userChrome.urlbar.iconbox_with_separator",       true);

user_pref("userChrome.findbar.floating_on_top",             true);

```

</details>

- **Arc Browser like theme**

Concept of proof for UI similar to [Arc Browser](https://thebrowser.company/).

https://user-images.githubusercontent.com/25581533/202938339-3776f55a-73b7-4686-a36a-6d3e1a456e16.mp4

First, Open `Customize toolbar`, then activate `Title Bar` or `Menu Bar`.

- **Addon:** [Sidebar Tabs](https://addons.mozilla.org/en-US/firefox/addon/sidebartabs/)
  - Or [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/), [Tab Center Reborn](https://addons.mozilla.org/en-US/firefox/addon/tabcenter-reborn/)
<details><summary><b>Configs</b></summary>

- `userChrome.hidden.tabbar` to `true`
- `userChrome.hidden.urlbar_iconbox` to `true`
- `userChrome.hidden.urlbar_iconbox.label_only` to `true`
- `userChrome.navbar.as_sidebar` to `true`
- `userChrome.urlView.as_commandbar` to `true`

</details>

**Additional context**

You can suggest compatibility issues, option names, etc.

### CODE REVIEW

**Comment by roland-rollo** [comment]
Is code for `Keyboard browsing` in this PR? I tried fresh profile with dev branch and with example `user.js` and it didn't work for me. I deleted from example all waterfox, photon or proton only lines.

**Comment by black7375** [comment]
Thank you for participating in the test.

This project does not use javascript, so you need to use add-ons.

- **Addon:** [Vim Vixen](https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/)
  - Or [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/), [Vimium-FF](https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/), [Saka Key](https://addons.mozilla.org/en-US/firefox/addon/saka-key/), [Surfingkeys](https://addons.mozilla.org/en-US/firefox/addon/surfingkeys_ff/)

---

In `user.js`, we can't run a typical javascript, and it's [designed to use only `user_pref()`](https://github.com/mozilla/gecko-dev/blob/master/modules/libpref/parser/src/lib.rs).

**Comment by roland-rollo** [comment]
I normally use `tridactyl` in my main profile. Sorry for dumb question, but if I need (let's say) `tridactyl` to do the magic, what change this PR will make for me?

**Comment by black7375** [comment]
This PR only reduces noise and provides a browser UI that suits `tridactyl`, so the change of `tridactyl` will not have a big impact.
Yes. It's just sugar.

Here is the main setting.
```js
user_pref("userChrome.tab.bar_separator",              true); // New setting

// -- User Chrome --------------------------------------------------------------
user_pref("userChrome.theme.monospace",                     true);

user_pref("userChrome.hidden.navbar",                       true);

user_pref("userChrome.counter.tab",                         true); // New setting
user_pref("userChrome.counter.bookmark_menu",               true); // New setting

user_pref("userChrome.tabbar.fill_width",                   true); // New setting

// -- User Content -------------------------------------------------------------
user_pref("userContent.page.monospace",                     true);
```

**Comment by roland-rollo** [comment]
Thanks, I understand now. I tested it and... looks very nice! It's nice addition to `tridactyl`. I use `sway` with hidden bar so it blends now even better.

**Pull request merged**
