### PR TITLE
Fix Minor Spelling Error for !important

### PR DESCRIPTION
**Pull request by rsquared226**

### CODE REVIEW

**Comment by rsquared226** [comment]
Thank you so much for making this! I love it so much, just found this minor spelling error

**Comment by black7375** [comment]
:+1:

**Comment by black7375** [comment]
@rsquared226 
I recently created a [CREDIT file](https://github.com/black7375/Firefox-UI-Fix/blob/master/CREDITS).
It is based on the commit log and github profile, please make sure the information is correct.

**Comment by rsquared226** [comment]
It's correct, thanks!

**Pull request merged**
