### PR TITLE
Move lepton stylesheets into their own files

### PR DESCRIPTION
**Pull request by anzz1**
**Describe the PR**

Move lepton stylesheets into their own files. This allows users to easily update lepton while still keeping
their own custom styles.

* Move userChrome.css -> leptonChrome.css
* Move userContent.css -> leptonContent.css
* Replace userChrome and userContent with stubs which import lepton

**Related Issue**
None

**Environment (please complete the following information):**

 - PR Type
   - [ ] `Add:` Add feature or enhanced.
   - [ ] `Fix:` Bug fix or change default values.
   - [x] `Clean:` Refactoring.
   - [ ] `Doc:` Update docs.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)

### CODE REVIEW

**Comment by anzz1** [comment]
Actually even better would be to put lepton inside it's own folder, like in this example here: https://github.com/stonecrusher/simpleMenuWizard/blob/master/userChrome.css

**Comment by black7375** [comment]
I think it's a good suggestion to make your custom easier.
It could be a bigger change than expected for those who have customized it before, so I will apply it in #351 and proceed it all at once.

**Comment by hdk5** [comment]
> Actually even better would be to put lepton inside it's own folder, like in this example here: https://github.com/stonecrusher/simpleMenuWizard/blob/master/userChrome.css

Just want to let you know that I had my lepton (with some personal extras) set up like this for quite a while, and also updated via git, and it works perfectly. [Like this.](https://user-images.githubusercontent.com/2550010/163341207-eedb7adb-a097-46d7-b502-f7acb33692e4.png)

So yeah, I think providing advanced setup instructions would work better.

**Comment by anzz1** [comment]
@hdk5 , oh yeah. Of course. How on earth did I not think about that? That is definitely the best course of action. Doing it like that works perfectly as-is right now, one idea for improvement would be to maybe edit the installation guide and the installation script though.

One way it could be improved imo, to maybe make it download the github repo to its' own "lepton" folder under the "chrome" like @hdk5 has it, and then check whether the files user.js, userchrome.css and usercontent.css exist already. If not, create the stubs for loading lepton, if yes, show a message to user "you have a existing theme/user.js settings installed, do you want to overwrite it with stubs [y/n] y = overwrite , n = show information about what import lines you need to add manually.

This is kinda low-priority though, I mean it could be good to include it as a part of the larger overhaul when it's changing a major version number and a restructure anyway, but if you probably have more important stuff to do and strapped on time, this is not too important to do right now.

In any case this particular PR is obsolote and can be closed, or if you want to keep it as an open PR for the discussion part (and as a "reminder"), that's good too. Whichever you think is best.

**Comment by black7375** [comment]
Recently, I've been working on cutomize script.
I think the structure of @hdk5 is quite good because VCS is independent.
There is certainly less risk of conflict.

**Comment by black7375** [comment]
I have written a simple script.

```shell
bash -c "$(curl -fsSL https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/custom/install.sh)"
```
```powershell
Powershell -c "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iwr https://raw.githubusercontent.com/black7375/Firefox-UI-Fix/custom/install.ps1 -useb | iex"
```

When installing or updating, it applies if you have `user-overrides.js`, `userChrome-overrides.css`, `userContent-overrides.css` files in the current directory (priority high) or installation(`<Firefox_Profile>/chrome/`) directory.

**Comment by black7375** [comment]
This proposal was reflected in #351

**Pull request closed without merging**
