### PR TITLE
Add workflow and update script and rename

### PR DESCRIPTION
**Pull request by 7k5x**
As you know, Linux and MacOS are case sensitive. Please don't use capitals in filenames.
This script currently supports:
 - [x] one profile quick install
 - [x] nightly
 - [x] multiple profiles

I learned a bit of switch code syntax.
This works pretty well in my case.
This thing doesn't run with `sh install.sh`.(`zsh install.sh` won't run as well.)
PLEASE USE `bash install.sh` or `env bash sh` to install!!!! <<<THIS IS VERY IMPORTTANT!!!

### CODE REVIEW

**Comment by 7k5x** [comment]
@black7375 I removed the fake commit. Is it okay now?

**Comment by black7375** [comment]
If you keep it open, we will clean it up and merge it later through force push.

**Comment by 7k5x** [comment]
Thank you despite my lack of knowledge about code.

**Comment by 7k5x** [comment]
@black7375 Does it work on your machine too?

**Comment by black7375** [comment]
Currently, I'am focusing on bug fixes, so I will start working on it after 1.0.

**Review by av884456 — APPROVED** [review]

**Comment by 7k5x** [comment]
@black7375 Is it still to early for a installer?

**Comment by black7375** [comment]
I will start right after we finish up to the context menu icon.

**Comment by 7k5x** [comment]
I’ll be waiting. Don’t hurry up I just wanted to know tbc

**Comment by 7k5x** [comment]
If the installer gets merged, I’ll work real hard on the wiki to give a precise direction and a powershell installer script too. I promise I could be really helpful on non-CSS(therefore additional but could make the project prettier and more attractive, easy to use for beginners etc)stuff!

**Comment by 7k5x** [comment]
#87 should be included in this script too. I’ll work on this next week.

**Comment by 7k5x** [comment]
Adding more stuff. The current script is working pretty great, but it has some flaws. Will open another later on.

**Pull request closed without merging**
