### PR TITLE
Ver 8.0.0 Feedback Thread

### PR DESCRIPTION
**Pull request by black7375**
**Describe the PR**

Mode
- Standard(v117 or higher) & ESR mode #744

Theme
- Windows 11 Color (Sun Valley): using `userChrome.compatibility.os.win11`
- `userChrome.theme.private`: Private color
- `userChrome.theme.non_native_menu`: only for linux(emulate windows menu)

Transparent
- `userChrome.theme.transparent.frame`
- `userChrome.theme.transparent.menu` #585
- `userChrome.theme.transparent.panel`

Hidden
- `userChrome.hidden.private_indicator`

Tab
- `userChrome.tab.container.on_top` #478
- `userChrome.tab.sound_with_favicons.on_center` #463
- `userChrome.tab.selected_bold`

User Content
- `userContent.newTab.background_image`
```css
@-moz-document url("about:home"), url("about:newtab") {
  body {
    --uc-newTab-wallpaper: url("YOUR_IMAGE_PATH");
  }
}
```
- `userContent.page.dark_mode.pdf`

### CODE REVIEW

**Comment by thunderstone135** [comment]
I used the leptonChrome.css and leptonContent.css and it works just fine with Waterfox G6 Beta.

**Comment by thunderstone135** [comment]
It also didn't interfere with the personal modifications I added in userChrome.css.

**Comment by rockenren** [comment]
There is a typo in directory name.
image

**Comment by black7375** [comment]
@rockenren  Thank you very much.
I worked manually due to CI issues. I think there was a problem in the process
I just updated and uploaded them again.

**Comment by Kinmfer** [comment]
In addition to setting userChrome.compatibility.os.win11 to true and installing micaforeveryone, what else should be set to experience Windows 11 Color (Sun Valley)?

**Comment by black7375** [comment]
@Kinmfer
Do you want a Sun valley color?

Just
- `userChrome.compatibility.os.win11` to `true`
- Use system theme
image

If you want to enable Mica, try with
- `userChrome.theme.transparent.frame` to `true`.
- [Mica For Everyone!](https://github.com/MicaForEveryone/MicaForEveryone)

Mika may be unstable because it has not yet been fully tested.

**Comment by Kinmfer** [comment]
>

OK, I'll try. Thank you very much, love this project, make my firefox look better

**Pull request merged**
