### PR TITLE
Add: Tab bar accent color on windows

### PR DESCRIPTION
**Pull request by medhefgo**

### CODE REVIEW

**Comment by black7375** [comment]
I only use Windows at home, so I'll test it tomorrow night.

Thank you

**Comment by black7375** [comment]
@medhefgo 
This code predicts that A will be in effect when `Title bars and window borders` activated.

image
[image refer](https://winaero.com/enable-dark-title-bars-custom-accent-color-windows-10/)

I tested the code with and without the code, but I couldn't find a difference.
It always looks like this.

Actvive
image
Inactive
image

Do you have any before and after screenshots or methods I'm missing?

**Comment by medhefgo** [comment]
This only works for the "System Theme" firefox theme. This mirrors the behavior with pre-proton, btw.
image

**Comment by black7375** [comment]
Is this the intended behavior?
It works fine in window's light mode.
image

Dark mode does not change the background color.
image

Is this the intended behavior?

**Comment by black7375** [comment]
**Photon Test Result**
image

The behavior in dark mode seems to have to be fixed.
Let's find out where is wrong.

**Comment by medhefgo** [comment]
Actually, this behavior also happens with photon, so I guess it works as intended? :D

Any, it should be fixed now.

**Comment by black7375** [comment]
Very cool work.
Many Windows users will love it.
image

**Comment by black7375** [comment]
Added two more situations and separated them into Windows Themes.

**URL Bar**
photon url bar accent color
lepton url bar accent color

**URL Search Menu**
photon url search menu
lepton url search menu

---

Just before the 1.0 release, the license and credit files will be added and will be added to the list of major contributors.

**Comment by black7375** [comment]
@medhefgo 
I recently created a [CREDIT file](https://github.com/black7375/Firefox-UI-Fix/blob/master/CREDITS).
It is based on the commit log and github profile, please make sure the information is correct.

**Pull request merged**
