### PR TITLE
Improve icons

### PR DESCRIPTION
**Pull request by black7375**
**Describe the PR**

Awesome icon pack by @zapSNH

**PR Type**

- [x] `Add:` Add feature or enhanced.
- [ ] `Fix:` Bug fix or change default values.
- [ ] `Clean:` Refactoring.
- [ ] `Doc:` Update docs.

**Related Issue**

#213

**Screenshots**

**Additional context**

The commit record was preserved as much as possible using `git cherrypick`.
It is still necessary to replace the default icons.

### CODE REVIEW

**Comment by zapSNH** [comment]
`screenshoot-1.svg` had some minor issues (it was slightly cut off to the right) and was misspelled (screenshoot-1.svg > screenshot-1.svg). Could you please add those fixes? 

https://github.com/zapSNH/lepton-icons/

**Comment by zapSNH** [comment]
It seems like you didn't push https://github.com/zapSNH/lepton-icons/commit/beba3f97aa24d512197c15e68390c4b0b9a60a4d which fixes the screenshot icon being slightly clipped to the right.

**Comment by black7375** [comment]
@zapSNH Now updated to your icon to apply.
Would you like to check if there's a missing part?
image

**Comment by zapSNH** [comment]
More tools in the app menu
image

**Comment by black7375** [comment]
Thanks, that's a applied.

**Comment by black7375** [comment]
Can we merge this PR?

**Comment by zapSNH** [comment]
Sure.

**Comment by black7375** [comment]
Once again, thank you for your great contribution

**Pull request merged**
