### PR TITLE
Windows PowerShell 5 installer

### PR DESCRIPTION
**Pull request by jammehcow**
This PR aims to create a Windows installer using the PowerShell scripting language. The installer should be functionally the same as the bash installer - including the same argument name/value input.

Design decisions:
 - A minimum PS version of 5 chosen due to it being default on Win 10. Win 7 has 2.0 by default so maybe this should be a target?
 - Script arguments also have a PowerShell-like alias - allowing either the bash param name or alias to be used

### CODE REVIEW

**Comment by jammehcow** [comment]
Haven't copied the prototype into this PR as it has no UI support. If anyone has any suggestions on PS UI libraries then shoot - otherwise I'll likely write a custom one just for this.

**Comment by black7375** [comment]
Thanks your contirbute
LGTM

**Comment by jammehcow** [comment]
@black7375 do you have any opinions on the minimum Windows version to support?
Currently this script is aiming for PowerShell v5 which comes default with Windows 10. If you want it to go back to Windows 7 it'll have to be PowerShell v2.

**Comment by 7k5x** [comment]
Can I ask a question? What do those dots mean?
image

**Comment by black7375** [comment]
Since Windows 7 is already supported, it is best to use 7 as the standard.
bash is also written based on older versions of Mac.

**Comment by jammehcow** [comment]
> Can I ask a question? What do those dots mean?

It's formatting for the help message you get when using the `-?` argument.
See here for more info: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comment_based_help?view=powershell-5.1

**Comment by jammehcow** [comment]
> Since Windows 7 is already supported, it is best to use Powershell V2 as the standard.

I'll see how I go with the limited functionality of V2 then. Might be some interesting behaviour since docs only go back to 5.1.

**Comment by black7375** [comment]
Run like this

```pwsh
Powershell -c "iwr https://raw.githubusercontent.com/jammehcow/Firefox-UI-Fix/feature/powershell5-install/Install.ps1 -useb | iex"
```

**Comment by jammehcow** [comment]
Sorry for bombing out on this PR. I'll do a proper review of your changes this weekend and submit another PR if there's anything I pick up on. Nice work though!

**Comment by black7375** [comment]
Prototype was a big help in the beginning.
Current code is written in a way that doesn't fit with PowerShell. (Simply porting to save time)
Maybe there's some bugs.

**Pull request merged**
