### PR TITLE
Add installer(Ver 1.5)

### PR DESCRIPTION
**Pull request by 7k5x**
In #87 where @travisnewman mentioned https://github.com/ideaweb/firefox-safari-style , the project says:
>To update please just run git pull in the cloned repository or just re-download it.

What this means is that if the user has already cloned the repository, fast-forwarding to the current repository and re-running `./install.sh` is how to update the theme, so I have concluded that embedding `git pull` in the script is not needed since people who downloaded the `.zip` would not have the `.git` folder, so it would be very confusing and will error out. That will be a `noadd`.

#48 is considerable, but needs a large amount of `if`s to implement and is a nice-to-have that is not necessary.

How about merging this first, and adding the nice-to-haves later on since I am not your exclusive shell scripter.

### CODE REVIEW

**Comment by black7375** [comment]
Can only README.org updates be reverted?

**Comment by black7375** [comment]
Just merge and then I'll do it.

**Comment by 7k5x** [comment]
@black7375 Thanks for letting me contribute!

**Comment by black7375** [comment]
From now on, please do not post the same PR repeatedly. #39 #42 #44 #60 #61
It's like spam.

**Comment by 7k5x** [comment]
@black7375 OK. I’ll review my code thoroughly and will post an issue mentioning it before PRing.

**Comment by 7k5x** [comment]
@black7375 I’m deeply sorry if you’re annoyed by by spammy pull requests.

**Comment by 7k5x** [comment]
@black7375 I found a compatibility issue with the installer script. Would you please add a dot after find in install.sh? I’ve found out that FreeBSD/MacOS wont’t work when the command is ‘find -maxdepth 1’ instead of ‘find . -maxdepth 1’.

**Comment by black7375** [comment]
> I found a compatibility issue with the installer script. Would you please add a dot after find in install.sh? I’ve found out that FreeBSD/MacOS wont’t work when the command is find -maxdepth 1 instead of find . -maxdepth 1(SC2185).

This will be corrected later.

---

To be honest, I want you to refrain from excessive mentions and comments that are divided into several.

Even in non-essential situations, notifications from the Github app are sent immediately every time, and it clutters up the notification window of the person who pressed watch on the project.
Each comment can be edited, so I think it's best to make the most of it.

Finally, don't be swear word.
https://github.com/black7375/Firefox-UI-Fix/pull/60#issuecomment-854781048
> wtf I wait I didn't mean to do that

That's why I added [CODE_OF_CONDUCT](https://github.com/black7375/Firefox-UI-Fix/blob/master/CODE_OF_CONDUCT.md).

**Pull request merged**
