### PR TITLE
SUMO and AMO Fixes

### PR DESCRIPTION
**Pull request by andmagdo**
**Describe the PR**
Certain dialog boxes in SUMO were not fixed. AMO/developers was missing fixes. Now accounts.firefox.org (I stupidly called it AMO too lol)

**Environment (please complete the following information):**

 - PR Type
   - [x] `Add:` Add feature or enhanced.
   - [ ] `Fix:` Bug fix or change default values.
   - [ ] `Clean:` Refactoring.
   - [ ] `Doc:` Update docs.
 - Distribution
   - [x] [Original Lepton](https://github.com/black7375/Firefox-UI-Fix)
   - [x] [Lepton's photon style](https://github.com/black7375/Firefox-UI-Fix/tree/photon-style)
   - [x] [Lepton's proton style](https://github.com/black7375/Firefox-UI-Fix/tree/proton-style)
Will work on every one
**Additional context**
N/A

### CODE REVIEW

**Comment by andmagdo** [comment]
I would also like to note that as far as I know, the fixes I have been sending have not been reflected in the other "themes," meaning new users of the non-default branch will not be benefited.

**Comment by black7375** [comment]
Overall it looks good.
Could you provide before/after screenshots & url?

---

I will release it soon so that it will be reflected in other themes.

**Comment by andmagdo** [comment]
image 
to 
image
and
image
to 
image

and lastly,
image
to
image

I did think I fixed the white background of the button, but I guess not

**Comment by andmagdo** [comment]
The site addresses are

1. any SUMO issue
2. https://addons.mozilla.org/en-US/developers/
3. https://accounts.firefox.com/settings

**Comment by black7375** [comment]
Thank you for your PR and efforts.

**Comment by andmagdo** [comment]
Of course, I am happy to help with software that I use, especially if it helps others

**Pull request merged**
