### PR TITLE
"WHY Not Proton" -> "Why NOT Proton"

### PR DESCRIPTION
**Pull request by Jonta**
Emphasis on the "not" differentiates it from the "WHY Proton"-heading

### CODE REVIEW

**Comment by black7375** [comment]
It makes sense.

Let's apply it first. (However, it may be rolled back later.)

**Comment by Jonta** [comment]
:)

Why might it be rolled back later? A part of the build process?

**Comment by black7375** [comment]
`WHY` is when it is judged to be better in terms of consistency and continuity.

**Comment by Jonta** [comment]
> `WHY` is when it is judged to be better in terms of consistency and continuity.

@black7375 I don't understand. Judged by whom?

**Comment by black7375** [comment]
Mainly the final decision is me.
It may be somewhat subjective.

**Pull request merged**
