### PR TITLE
Added missing punctuation, and some tweaks to README.org

### PR DESCRIPTION
**Pull request by Patricek0056**
NOTE: I replaced the three dots “...” with horizontal ellipsis Unicode character “…” in the README.org file, so if there would be character encoding problems, then reverse this change.
If you dislike this change, then don't approve the commit, and if you like it, then please don't mark me as contributor, because I don't deserve the contributor place.

**Describe the PR**
Some little changes to the README.org file.

**PR Type**

- [ ] `Add:` Add feature or enhanced.
- [ ] `Fix:` Bug fix or change default values.
- [ ] `Clean:` Refactoring.
- [x] `Doc:` Update docs.

### CODE REVIEW

**Comment by Patricek0056** [comment]
Sorry, the title has typo. No Punctation, but Punctuation.

**Review by black7375 — CHANGES_REQUESTED** [review]
3dot to unicode looks good, but I don't think the comma and the period are needed for the list.

**Comment by Patricek0056** [comment]
Should I change it?

**Comment by black7375** [comment]
Yes, please remove comma(`,`) and period(`.`).

**Comment by Patricek0056** [comment]
Okay, I deleted them.

**Comment by Patricek0056** [comment]
Thank you

**Pull request merged**
